# Generated by Django 6.0.8 on 2026-08-05 19:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompatibility',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('equipment_brand', models.CharField(db_index=True, max_length=120)),
                ('equipment_model', models.CharField(db_index=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part_product', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'product_kind': 'spare_part'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product')),
            ],
            options={
                'verbose_name': 'historical compatibilidade',
                'verbose_name_plural': 'historical compatibilidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_brand', models.CharField(db_index=True, max_length=120)),
                ('equipment_model', models.CharField(db_index=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_product', models.ForeignKey(limit_choices_to={'product_kind': 'spare_part'}, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='products.product')),
            ],
            options={
                'verbose_name': 'compatibilidade',
                'verbose_name_plural': 'compatibilidades',
                'ordering': ('equipment_brand', 'equipment_model', 'part_product_id'),
                'indexes': [models.Index(fields=['equipment_brand', 'equipment_model'], name='compat_brand_model_idx')],
                'constraints': [models.UniqueConstraint(fields=('equipment_brand', 'equipment_model', 'part_product'), name='uniq_compat_brand_model_part')],
            },
        ),
    ]
