# Generated by Django 6.0.8 on 2026-08-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('order_confirmation', 'Confirmação de pedido'), ('invoice', 'NF-e'), ('other', 'Outro')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('bounced', 'Bounce')], db_index=True, default='queued', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('bounce_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'log de e-mail',
                'verbose_name_plural': 'logs de e-mail',
                'ordering': ('-created_at',),
            },
        ),
    ]
