# Generated by Django 6.0.8 on 2026-08-07 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_fase8"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sku", models.CharField(blank=True, db_index=True, max_length=64)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warranty_codes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "código de garantia",
                "verbose_name_plural": "códigos de garantia",
                "ordering": ("-created_at",),
            },
        ),
    ]
