# Generated by Django 6.0.8 on 2026-08-06 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cost", "Custo IA"),
                            ("sla", "SLA"),
                            ("error", "Erro recorrente"),
                            ("queue", "Fila"),
                            ("incident", "Incidente"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Aviso"), ("critical", "Crítico")],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("channel", models.CharField(blank=True, default="panel", max_length=64)),
                ("acknowledged", models.BooleanField(db_index=True, default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acked_ops_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "alerta operacional",
                "verbose_name_plural": "alertas operacionais",
                "ordering": ("-created_at",),
            },
        ),
    ]
