# Generated by Django 6.0.8 on 2026-08-08 19:05

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_fase7_ops_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, help_text='Eyebrow opcional (ex.: TECNOLOGIA AI)', max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('lead', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.dashboard.models.home_hero_image_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'slide do hero',
                'verbose_name_plural': 'slides do hero',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
