# Generated by Django 6.0.8 on 2026-08-05 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0001_initial"),
        ("products", "0002_historicalstock_productimage_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "Percentual"), ("fixed", "Valor fixo")],
                        default="percent",
                        max_length=16,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "cupom",
                "verbose_name_plural": "cupons",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="ProductPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("promo_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "promoção",
                "verbose_name_plural": "promoções",
            },
        ),
    ]
