# Generated by Django 6.0.8 on 2026-08-05 20:38

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="HistoricalReturnRequest",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refund", "Reembolso (arrependimento)"),
                            ("exchange", "Troca por outra peça"),
                        ],
                        default="refund",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("regret", "Arrependimento (CDC)"),
                            ("defect", "Defeito"),
                            ("wrong_item", "Item errado"),
                            ("other", "Outro"),
                        ],
                        default="regret",
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("under_review", "Em análise"),
                            ("approved", "Aprovado"),
                            ("rejected", "Recusado"),
                            ("refunded", "Reembolsado"),
                            ("exchanged", "Trocado"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=32,
                    ),
                ),
                ("delivered_at", models.DateTimeField()),
                ("deadline_at", models.DateTimeField()),
                ("refund_payment_id", models.CharField(blank=True, max_length=64)),
                ("staff_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical solicitação de troca/devolução",
                "verbose_name_plural": "historical solicitações de troca/devolução",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refund", "Reembolso (arrependimento)"),
                            ("exchange", "Troca por outra peça"),
                        ],
                        default="refund",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("regret", "Arrependimento (CDC)"),
                            ("defect", "Defeito"),
                            ("wrong_item", "Item errado"),
                            ("other", "Outro"),
                        ],
                        default="regret",
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("under_review", "Em análise"),
                            ("approved", "Aprovado"),
                            ("rejected", "Recusado"),
                            ("refunded", "Reembolsado"),
                            ("exchanged", "Trocado"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=32,
                    ),
                ),
                ("delivered_at", models.DateTimeField()),
                ("deadline_at", models.DateTimeField()),
                ("refund_payment_id", models.CharField(blank=True, max_length=64)),
                ("staff_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitação de troca/devolução",
                "verbose_name_plural": "solicitações de troca/devolução",
                "ordering": ("-created_at",),
            },
        ),
    ]
