# Generated by Django 6.0.8 on 2026-08-06 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_fase6_diagnostico_langgraph"),
        ("orders", "0002_f4d_coupons_returns"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="attribution_source",
            field=models.CharField(
                choices=[
                    ("direct", "Direto"),
                    ("chat", "Chat RAG"),
                    ("diagnosis", "Diagnóstico IA"),
                    ("photo", "Busca por foto"),
                ],
                db_index=True,
                default="direct",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="chat_session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ai.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="attribution_source",
            field=models.CharField(
                choices=[
                    ("direct", "Direto"),
                    ("chat", "Chat RAG"),
                    ("diagnosis", "Diagnóstico IA"),
                    ("photo", "Busca por foto"),
                ],
                db_index=True,
                default="direct",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="chat_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="ai.chatsession",
            ),
        ),
    ]
