# Generated by Django 6.0.8 on 2026-08-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_fase6_diagnostico_langgraph"),
        ("cart", "0002_f4d_coupons_returns"),
        ("orders", "0003_fase6_diagnostico_langgraph"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_orde_status_25e057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["email", "created_at"], name="orders_orde_email_4516f5_idx"),
        ),
    ]
