# Generated by Django 6.0.8 on 2026-08-06 23:42

import apps.ai.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_fase5_chat_rag"),
        ("products", "0002_historicalstock_productimage_stock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="diagnosis_card",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Card DiagnosticCardData (title, confidence, refManual, recommendedSkus).",
            ),
        ),
        migrations.CreateModel(
            name="PhotoSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("anonymous_key", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "image",
                    models.FileField(max_length=512, upload_to=apps.ai.models.photo_upload_to),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Em execução"),
                            ("done", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("candidates", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_searches",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "busca por foto",
                "verbose_name_plural": "buscas por foto",
                "ordering": ("-created_at",),
            },
        ),
    ]
