# Generated by Django 6.0.8 on 2026-08-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_fase8'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_provider',
            field=models.CharField(blank=True, default='mock', max_length=32),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
