# Generated by Django 6.0.8 on 2026-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartnerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("legal_name", models.CharField(blank=True, max_length=180)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("city", models.CharField(db_index=True, max_length=120)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("cep", models.CharField(blank=True, max_length=9)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "brands",
                    models.CharField(
                        blank=True,
                        help_text="Marcas atendidas, separadas por vírgula",
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "assistência parceira",
                "verbose_name_plural": "assistências parceiras",
                "ordering": ("state", "city", "name"),
                "indexes": [
                    models.Index(
                        fields=["state", "city", "active"], name="partners_pa_state_40fc08_idx"
                    )
                ],
            },
        ),
    ]
