# Generated by Django 6.0.8 on 2026-08-04 21:58

import apps.manuals.models
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('awaiting_review', 'Aguardando revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=32)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('raw_text_preview', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('corrected_json', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('langsmith_trace_id', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'log de extração',
                'verbose_name_plural': 'logs de extração',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalExtractionLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('awaiting_review', 'Aguardando revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=32)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('raw_text_preview', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('corrected_json', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('langsmith_trace_id', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical log de extração',
                'verbose_name_plural': 'historical logs de extração',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalManual',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('file', models.TextField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('source_locale', models.CharField(default='pt-BR', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('scan_status', models.CharField(choices=[('pending', 'Pendente'), ('clean', 'Limpo'), ('infected', 'Infectado'), ('skipped', 'Ignorado (dev)')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical manual',
                'verbose_name_plural': 'historical manuais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(max_length=512, upload_to=apps.manuals.models.manual_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('source_locale', models.CharField(default='pt-BR', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('scan_status', models.CharField(choices=[('pending', 'Pendente'), ('clean', 'Limpo'), ('infected', 'Infectado'), ('skipped', 'Ignorado (dev)')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'manual',
                'verbose_name_plural': 'manuais',
                'ordering': ('-created_at',),
            },
        ),
    ]
