# Generated by Django 6.0.8 on 2026-08-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionlog",
            name="langgraph_interrupted",
            field=models.BooleanField(
                default=False, help_text="True quando o grafo pausou aguardando revisão humana."
            ),
        ),
        migrations.AddField(
            model_name="extractionlog",
            name="langgraph_thread_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Thread LangGraph para pausa/retomada HITL (F6).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="historicalextractionlog",
            name="langgraph_interrupted",
            field=models.BooleanField(
                default=False, help_text="True quando o grafo pausou aguardando revisão humana."
            ),
        ),
        migrations.AddField(
            model_name="historicalextractionlog",
            name="langgraph_thread_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Thread LangGraph para pausa/retomada HITL (F6).",
                max_length=64,
            ),
        ),
    ]
