# Generated by Django 6.0.8 on 2026-08-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_fase6_diagnostico_langgraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionlog',
            name='prompt_version',
            field=models.CharField(default='v2', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalextractionlog',
            name='prompt_version',
            field=models.CharField(default='v2', max_length=32),
        ),
    ]
