# Generated by Django 6.0.8 on 2026-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0004_extraction_prompt_default_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionlog',
            name='prompt_version',
            field=models.CharField(default='v3', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalextractionlog',
            name='prompt_version',
            field=models.CharField(default='v3', max_length=32),
        ),
    ]
