# Generated by Django 6.0.8 on 2026-08-05 20:29

import apps.tickets.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_historicalstock_productimage_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossSellAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pdp', 'PDP'), ('email', 'E-mail pós-compra'), ('checker', 'Verificador')], default='pdp', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_sell_attributions', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_sell_wins', to='products.product')),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_sell_sources', to='products.product')),
            ],
            options={
                'verbose_name': 'atribuição cross-sell',
                'verbose_name_plural': 'atribuições cross-sell',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('equipment', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_analysis', 'Em Análise'), ('waiting_part', 'Aguardando Peça'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], db_index=True, default='open', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Normal'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=16)),
                ('origin', models.CharField(choices=[('site', 'Site'), ('chat', 'Chat IA'), ('email', 'E-mail'), ('internal', 'Interno')], default='site', max_length=16)),
                ('sla_due_at', models.DateTimeField(default=apps.tickets.models.default_sla_due)),
                ('sla_breached', models.BooleanField(db_index=True, default=False)),
                ('sla_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical chamado',
                'verbose_name_plural': 'historical chamados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('equipment', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_analysis', 'Em Análise'), ('waiting_part', 'Aguardando Peça'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], db_index=True, default='open', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Normal'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=16)),
                ('origin', models.CharField(choices=[('site', 'Site'), ('chat', 'Chat IA'), ('email', 'E-mail'), ('internal', 'Interno')], default='site', max_length=16)),
                ('sla_due_at', models.DateTimeField(default=apps.tickets.models.default_sla_due)),
                ('sla_breached', models.BooleanField(db_index=True, default=False)),
                ('sla_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chamado',
                'verbose_name_plural': 'chamados',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tickets.models.ticket_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('status_from', models.CharField(blank=True, max_length=32)),
                ('status_to', models.CharField(blank=True, max_length=32)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'evento de chamado',
                'verbose_name_plural': 'eventos de chamado',
                'ordering': ('created_at',),
            },
        ),
    ]
