# Generated by Django 6.0.8 on 2026-08-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_fase8"),
        ("products", "0003_fase8"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="origin",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("chat", "Chat IA"),
                    ("email", "E-mail"),
                    ("internal", "Interno"),
                    ("whatsapp", "WhatsApp"),
                    ("qr", "QR Garantia"),
                ],
                default="site",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="origin",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("chat", "Chat IA"),
                    ("email", "E-mail"),
                    ("internal", "Interno"),
                    ("whatsapp", "WhatsApp"),
                    ("qr", "QR Garantia"),
                ],
                default="site",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="crosssellattribution",
            index=models.Index(
                fields=["source", "created_at"], name="tickets_cro_source_60b333_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "sla_due_at"], name="tickets_tic_status_2383b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["origin", "created_at"], name="tickets_tic_origin_022c6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "priority", "created_at"], name="tickets_tic_status_58a686_idx"
            ),
        ),
    ]
