# Generated by Django 6.0.8 on 2026-08-04 21:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('manuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=16)),
                ('product_kind', models.CharField(choices=[('finished_good', 'Produto acabado'), ('spare_part', 'Peça de reposição')], default='finished_good', max_length=32)),
                ('brand', models.CharField(max_length=120)),
                ('model_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('voltage', models.CharField(blank=True, max_length=32)),
                ('power_w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manuals.manual')),
            ],
            options={
                'verbose_name': 'historical produto',
                'verbose_name_plural': 'historical produtos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=16)),
                ('product_kind', models.CharField(choices=[('finished_good', 'Produto acabado'), ('spare_part', 'Peça de reposição')], default='finished_good', max_length=32)),
                ('brand', models.CharField(max_length=120)),
                ('model_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('voltage', models.CharField(blank=True, max_length=32)),
                ('power_w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='manuals.manual')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='pt-BR', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name': 'tradução de produto',
                'verbose_name_plural': 'traduções de produto',
                'unique_together': {('product', 'locale')},
            },
        ),
    ]
