# Generated by Django 6.0.8 on 2026-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("manuals", "0003_fase6_diagnostico_langgraph"),
        ("products", "0002_historicalstock_productimage_stock_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "status", "sku"], name="products_pr_brand_953953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "published_at"], name="products_pr_status_8124bb_idx"
            ),
        ),
    ]
