# Generated by Django 6.0.8 on 2026-08-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_fase8'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producttranslation',
            index=models.Index(fields=['locale', 'name'], name='products_pr_locale_740876_idx'),
        ),
    ]
