# Generated by Django 6.0.8 on 2026-08-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_equipment_model'),
        ('products', '0004_tp5_translation_locale_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='equipment_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='equipment_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.equipmentmodel'),
        ),
    ]
