# Generated by Django 6.0.8 on 2026-08-13 20:48

from django.db import migrations, models


def forwards_backfill_categories(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    for product in Product.objects.filter(category_id__isnull=False).iterator():
        product.categories.add(product.category_id)


def backwards_clear_categories(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Through = Product.categories.through
    Through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_capitalize_category_names"),
        ("products", "0008_backfill_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products_m2m",
                to="catalog.category",
            ),
        ),
        migrations.RunPython(forwards_backfill_categories, backwards_clear_categories),
    ]
